name: Cypress API Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-binary-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install
      
      - name: Fix Cypress permissions
        run: chmod +x ./node_modules/.bin/cypress || true

      - name: Install Cypress binary
        run: npx cypress install

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/reports,json=true,overwrite=false,html=false


      - name: Fix Mochawesome permissions
        run: chmod +x ./node_modules/.bin/mochawesome-merge || true

      - name: List reports folder
        run: ls -la cypress/reports
      
      - name: Check JSON reports
        run: |
          echo "Listing JSON reports:"
          ls -la cypress/reports/*.json || echo "No JSON reports found!"

      - name: Merge Mochawesome reports
        run: |
          if ls cypress/reports/*.json 1> /dev/null 2>&1; then
            npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json
          else
            echo "{}" > cypress/reports/report.json
          fi



      - name: Generate Mochawesome HTML report
        run: npx marge cypress/reports/report.json --reportDir=cypress/reports --inline

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports
